# Generated by Django 4.0.4 on 2022-04-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
